services:
  api:
    image: friday-api:${TAG:-latest}
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - ./data:/app/data
    networks:
      - friday
networks:
  friday:
    driver: bridge
