services:
  api:
    image: friday-api:${TAG:-latest}
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - ./data:/app/data
    networks:
      - friday
  ui:
    image: friday-ui:${TAG:-latest}
    build:
      context: .
      dockerfile: Dockerfile.ui
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_API_URL=http://api:8080
    depends_on:
      - api
    networks:
      - friday
networks:
  friday:
    driver: bridge
