openapi: 3.0.1
info:
  contact:
    email: miniyu97@gmail.com
    name: meteormin
    url: https://github.com/meteormin/friday.go
  description: Friday.go API
  title: Friday.go API
  version: "{{.Version}}"
servers:
- url: "http://{{.Host}}/"
- url: "https://{{.Host}}/"
tags:
- name: auth
- name: users
- name: upload-file
- name: posts
paths:
  /api/posts:
    get:
      description: 포스트 리스트 조회 API
      operationId: posts.retrieve
      responses:
        "200":
          content:
            application/json:
              schema:
                items:
                  $ref: '#/components/schemas/internal_adapter_rest.PostResource'
                type: array
          description: 포스트 리스트 조회 성공
        "500":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/github_com_meteormin_friday_go_internal_app_errors.Error'
          description: 서버 오류
      summary: 포스트 리스트 조회
      tags:
      - posts
    post:
      description: 포스트 생성 API
      operationId: posts.create
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/internal_adapter_rest.CreatePostRequest'
        description: 포스트 생성 정보
        required: true
      responses:
        "201":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/internal_adapter_rest.PostResource'
          description: 포스트 생성 성공
        "400":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/github_com_meteormin_friday_go_internal_app_errors.Error'
          description: 잘못된 요청
        "409":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/github_com_meteormin_friday_go_internal_app_errors.Error'
          description: 이메일 중복
        "500":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/github_com_meteormin_friday_go_internal_app_errors.Error'
          description: 서버 오류
      summary: 포스트 생성
      tags:
      - posts
      x-codegen-request-body-name: req
  /api/posts/{id}:
    delete:
      description: 포스트 삭제 API
      operationId: posts.delete
      parameters:
      - description: 포스트 ID
        in: path
        name: id
        required: true
        schema:
          type: integer
      responses:
        "204":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/internal_adapter_rest.PostResource'
          description: 포스트 삭제 성공
        "404":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/github_com_meteormin_friday_go_internal_app_errors.Error'
          description: 존재하지 않는 포스트
        "500":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/github_com_meteormin_friday_go_internal_app_errors.Error'
          description: 서버 오류
      summary: 포스트 삭제
      tags:
      - posts
    get:
      description: 포스트 조회 API
      operationId: posts.find
      parameters:
      - description: 포스트 ID
        in: path
        name: id
        required: true
        schema:
          type: integer
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/internal_adapter_rest.PostResource'
          description: 포스트 조회 성공
        "400":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/github_com_meteormin_friday_go_internal_app_errors.Error'
          description: 잘못된 요청
        "500":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/github_com_meteormin_friday_go_internal_app_errors.Error'
          description: 서버 오류
      summary: 포스트 조회
      tags:
      - posts
    put:
      description: 포스트 수정 API
      operationId: posts.update
      parameters:
      - description: 포스트 ID
        in: path
        name: id
        required: true
        schema:
          type: integer
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/internal_adapter_rest.UpdatePostRequest'
        description: 포스트 수정 정보
        required: true
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/internal_adapter_rest.PostResource'
          description: 포스트 수정 성공
        "400":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/github_com_meteormin_friday_go_internal_app_errors.Error'
          description: 잘못된 요청
        "500":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/github_com_meteormin_friday_go_internal_app_errors.Error'
          description: 서버 오류
      summary: 포스트 수정
      tags:
      - posts
      x-codegen-request-body-name: req
  /api/sites:
    post:
      description: 사이트 생성 API
      operationId: sites.create
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/internal_adapter_rest.CreateSiteRequest'
        description: 사이트 생성 정보
        required: true
      responses:
        "201":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/internal_adapter_rest.SiteResource'
          description: 사이트 생성 성공
        "400":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/github_com_meteormin_friday_go_internal_app_errors.Error'
          description: 잘못된 요청
        "409":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/github_com_meteormin_friday_go_internal_app_errors.Error'
          description: 이메일 중복
        "500":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/github_com_meteormin_friday_go_internal_app_errors.Error'
          description: 서버 오류
      summary: 사이트 생성
      tags:
      - sites
      x-codegen-request-body-name: req
  /api/sites/{id}:
    delete:
      description: 사이트 삭제 API
      operationId: sites.delete
      parameters:
      - description: 사이트 ID
        in: path
        name: id
        required: true
        schema:
          type: integer
      responses:
        "204":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/internal_adapter_rest.SiteResource'
          description: 사이트 삭제 성공
        "400":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/github_com_meteormin_friday_go_internal_app_errors.Error'
          description: 잘못된 요청
        "404":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/github_com_meteormin_friday_go_internal_app_errors.Error'
          description: 사이트 없음
        "500":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/github_com_meteormin_friday_go_internal_app_errors.Error'
          description: 서버 오류
      summary: 사이트 삭제
      tags:
      - sites
    get:
      description: 사이트 조회 API
      operationId: sites.find
      parameters:
      - description: 사이트 ID
        in: path
        name: id
        required: true
        schema:
          type: integer
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/internal_adapter_rest.SiteResource'
          description: 사이트 조회 성공
        "400":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/github_com_meteormin_friday_go_internal_app_errors.Error'
          description: 잘못된 요청
        "404":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/github_com_meteormin_friday_go_internal_app_errors.Error'
          description: 사이트 없음
      summary: 사이트 조회
      tags:
      - sites
    put:
      description: 사이트 수정 API
      operationId: sites.update
      parameters:
      - description: 사이트 ID
        in: path
        name: id
        required: true
        schema:
          type: integer
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/internal_adapter_rest.UpdateSiteRequest'
        description: 사이트 수정 정보
        required: true
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/internal_adapter_rest.SiteResource'
          description: 사이트 수정 성공
        "400":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/github_com_meteormin_friday_go_internal_app_errors.Error'
          description: 잘못된 요청
        "404":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/github_com_meteormin_friday_go_internal_app_errors.Error'
          description: 사이트 없음
        "500":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/github_com_meteormin_friday_go_internal_app_errors.Error'
          description: 서버 오류
      summary: 사이트 수정
      tags:
      - sites
      x-codegen-request-body-name: req
  /api/sites/{id}/posts:
    get:
      description: 사이트 포스트 리스트 조회 API
      operationId: sites.retrievePosts
      parameters:
      - description: 사이트 ID
        in: path
        name: id
        required: true
        schema:
          type: integer
      responses:
        "200":
          content:
            application/json:
              schema:
                items:
                  $ref: '#/components/schemas/internal_adapter_rest.PostResource'
                type: array
          description: 사이트 포스트 리스트 조회 성공
        "400":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/github_com_meteormin_friday_go_internal_app_errors.Error'
          description: 잘못된 요청
        "404":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/github_com_meteormin_friday_go_internal_app_errors.Error'
          description: 사이트 없음
      summary: 사이트 포스트 리스트 조회
      tags:
      - sites
  /api/upload-file:
    post:
      description: 파일 업로드 API
      operationId: files.upload
      requestBody:
        content:
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/files_upload_request'
        required: true
      responses:
        "201":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/internal_adapter_rest.UploadFileResponse'
          description: 파일 업로드 성공
        "400":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/github_com_meteormin_friday_go_internal_app_errors.Error'
          description: 잘못된 요청
        "500":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/github_com_meteormin_friday_go_internal_app_errors.Error'
          description: 서버 오류
      summary: 파일 업로드
      tags:
      - upload-file
  /auth/me:
    get:
      description: 회원 정보 조회 API
      operationId: me
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/internal_adapter_rest.UserResource'
          description: 회원 정보 조회 성공
        "401":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/github_com_meteormin_friday_go_internal_app_errors.Error'
          description: 로그인 정보 없음
        "500":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/github_com_meteormin_friday_go_internal_app_errors.Error'
          description: 서버 오류
      summary: 회원 정보 조회
      tags:
      - auth
  /auth/sign-in:
    post:
      description: 회원 로그인 API
      operationId: sign-in
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/internal_adapter_rest.SignInRequest'
        description: 회원 로그인 정보
        required: true
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/internal_adapter_rest.TokenResource'
          description: 회원 로그인 성공
        "400":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/github_com_meteormin_friday_go_internal_app_errors.Error'
          description: 잘못된 요청
        "401":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/github_com_meteormin_friday_go_internal_app_errors.Error'
          description: 로그인 실험
        "500":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/github_com_meteormin_friday_go_internal_app_errors.Error'
          description: 서버 오류
      summary: 회원 로그인
      tags:
      - auth
      x-codegen-request-body-name: req
  /auth/sign-up:
    post:
      description: 회원 가입 API
      operationId: sign-up
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/internal_adapter_rest.SignupRequest'
        description: 회원 가입 정보
        required: true
      responses:
        "201":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/internal_adapter_rest.UserResource'
          description: 회원 가입 성공
        "400":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/github_com_meteormin_friday_go_internal_app_errors.Error'
          description: 잘못된 요청" errors.ErrInvalidUserPassword
        "409":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/github_com_meteormin_friday_go_internal_app_errors.Error'
          description: 이메일 중복" errors.ErrDuplicateUserUsername
        "500":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/github_com_meteormin_friday_go_internal_app_errors.Error'
          description: 서버 오류
      summary: 회원 가입
      tags:
      - auth
      x-codegen-request-body-name: req
  /users:
    get:
      description: 회원 리스트 조회 API
      operationId: users
      responses:
        "200":
          content:
            application/json:
              schema:
                items:
                  $ref: '#/components/schemas/internal_adapter_rest.UserResource'
                type: array
          description: 회원 리스트 조회 성공
        "500":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/github_com_meteormin_friday_go_internal_app_errors.Error'
          description: 서버 오류
      summary: 회원 리스트 조회
      tags:
      - users
components:
  schemas:
    github_com_meteormin_friday_go_internal_app_errors.Error:
      example:
        code: 6
        message: message
        title: title
      properties:
        code:
          type: integer
        message:
          type: string
        title:
          type: string
      type: object
    internal_adapter_rest.CreatePostRequest:
      description: 생성 요청
      properties:
        content:
          type: string
        fileId:
          type: integer
        siteId:
          type: integer
        tags:
          items:
            type: string
          type: array
        title:
          type: string
      type: object
    internal_adapter_rest.CreateSiteRequest:
      properties:
        host:
          type: string
        name:
          type: string
      type: object
    internal_adapter_rest.PostResource:
      example:
        updated_at: updated_at
        created_at: created_at
        id: 0
        title: title
        uri: uri
        content: content
        tags:
        - tags
        - tags
      properties:
        content:
          type: string
        created_at:
          type: string
        id:
          type: integer
        tags:
          items:
            type: string
          type: array
        title:
          type: string
        updated_at:
          type: string
        uri:
          type: string
      type: object
    internal_adapter_rest.SignInRequest:
      description: 로그인 요청
      properties:
        password:
          type: string
        username:
          type: string
      type: object
    internal_adapter_rest.SignupRequest:
      description: 가입 요청
      properties:
        name:
          type: string
        password:
          type: string
        username:
          type: string
      type: object
    internal_adapter_rest.SiteResource:
      example:
        host: host
        name: name
        id: 0
      properties:
        host:
          type: string
        id:
          type: integer
        name:
          type: string
      type: object
    internal_adapter_rest.TokenResource:
      description: 토큰 정보 리소스
      example:
        exp: 0
        token: token
      properties:
        exp:
          type: integer
        token:
          type: string
      type: object
    internal_adapter_rest.UpdatePostRequest:
      properties:
        content:
          type: string
        fileId:
          type: integer
        tags:
          items:
            type: string
          type: array
        title:
          type: string
      type: object
    internal_adapter_rest.UpdateSiteRequest:
      properties:
        name:
          type: string
      type: object
    internal_adapter_rest.UploadFileResponse:
      example:
        id: 0
        url: url
      properties:
        id:
          type: integer
        url:
          type: string
      type: object
    internal_adapter_rest.UserResource:
      description: 회원 정보 리소스
      example:
        createdAt: createdAt
        name: name
        updatedAt: updatedAt
        username: username
      properties:
        createdAt:
          type: string
        name:
          type: string
        updatedAt:
          type: string
        username:
          type: string
      type: object
    files_upload_request:
      properties:
        file:
          description: 파일
          format: binary
          type: string
      required:
      - file
      type: object
  securitySchemes:
    BearerAuth:
      in: header
      name: Authorization
      type: apiKey
x-original-swagger-version: "2.0"
