// Package api Code generated by swaggo/swag. DO NOT EDIT
package api

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {
            "name": "meteormin",
            "url": "https://github.com/meteormin/friday.go",
            "email": "miniyu97@gmail.com"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/api/auth/me": {
            "get": {
                "description": "회원 정보 조회 API",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "회원 정보 조회",
                "operationId": "me",
                "responses": {
                    "200": {
                        "description": "회원 정보 조회 성공",
                        "schema": {
                            "$ref": "#/definitions/internal_adapter_rest.UserResource"
                        }
                    },
                    "401": {
                        "description": "로그인 정보 없음",
                        "schema": {
                            "$ref": "#/definitions/github_com_meteormin_friday_go_internal_app_errors.Error"
                        }
                    },
                    "500": {
                        "description": "서버 오류",
                        "schema": {
                            "$ref": "#/definitions/github_com_meteormin_friday_go_internal_app_errors.Error"
                        }
                    }
                }
            }
        },
        "/api/auth/sign-in": {
            "post": {
                "description": "회원 로그인 API",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "회원 로그인",
                "operationId": "sign-in",
                "parameters": [
                    {
                        "description": "회원 로그인 정보",
                        "name": "req",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/internal_adapter_rest.SignInRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "회원 로그인 성공",
                        "schema": {
                            "$ref": "#/definitions/internal_adapter_rest.TokenResource"
                        }
                    },
                    "400": {
                        "description": "잘못된 요청",
                        "schema": {
                            "$ref": "#/definitions/github_com_meteormin_friday_go_internal_app_errors.Error"
                        }
                    },
                    "401": {
                        "description": "로그인 실험",
                        "schema": {
                            "$ref": "#/definitions/github_com_meteormin_friday_go_internal_app_errors.Error"
                        }
                    },
                    "500": {
                        "description": "서버 오류",
                        "schema": {
                            "$ref": "#/definitions/github_com_meteormin_friday_go_internal_app_errors.Error"
                        }
                    }
                }
            }
        },
        "/api/auth/sign-up": {
            "post": {
                "description": "회원 가입 API",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "회원 가입",
                "operationId": "sign-up",
                "parameters": [
                    {
                        "description": "회원 가입 정보",
                        "name": "req",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/internal_adapter_rest.SignupRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "회원 가입 성공",
                        "schema": {
                            "$ref": "#/definitions/internal_adapter_rest.UserResource"
                        }
                    },
                    "400": {
                        "description": "잘못된 요청\" errors.ErrInvalidUserPassword",
                        "schema": {
                            "$ref": "#/definitions/github_com_meteormin_friday_go_internal_app_errors.Error"
                        }
                    },
                    "409": {
                        "description": "이메일 중복\" errors.ErrDuplicateUserUsername",
                        "schema": {
                            "$ref": "#/definitions/github_com_meteormin_friday_go_internal_app_errors.Error"
                        }
                    },
                    "500": {
                        "description": "서버 오류",
                        "schema": {
                            "$ref": "#/definitions/github_com_meteormin_friday_go_internal_app_errors.Error"
                        }
                    }
                }
            }
        },
        "/api/posts": {
            "get": {
                "description": "포스트 리스트 조회 API",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "posts"
                ],
                "summary": "포스트 리스트 조회",
                "operationId": "posts.retrieve",
                "responses": {
                    "200": {
                        "description": "포스트 리스트 조회 성공",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/internal_adapter_rest.PostResource"
                            }
                        }
                    },
                    "500": {
                        "description": "서버 오류",
                        "schema": {
                            "$ref": "#/definitions/github_com_meteormin_friday_go_internal_app_errors.Error"
                        }
                    }
                }
            },
            "post": {
                "description": "포스트 생성 API",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "posts"
                ],
                "summary": "포스트 생성",
                "operationId": "posts.create",
                "parameters": [
                    {
                        "description": "포스트 생성 정보",
                        "name": "req",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/internal_adapter_rest.CreatePostRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "포스트 생성 성공",
                        "schema": {
                            "$ref": "#/definitions/internal_adapter_rest.PostResource"
                        }
                    },
                    "400": {
                        "description": "잘못된 요청",
                        "schema": {
                            "$ref": "#/definitions/github_com_meteormin_friday_go_internal_app_errors.Error"
                        }
                    },
                    "409": {
                        "description": "이메일 중복",
                        "schema": {
                            "$ref": "#/definitions/github_com_meteormin_friday_go_internal_app_errors.Error"
                        }
                    },
                    "500": {
                        "description": "서버 오류",
                        "schema": {
                            "$ref": "#/definitions/github_com_meteormin_friday_go_internal_app_errors.Error"
                        }
                    }
                }
            }
        },
        "/api/posts/{id}": {
            "get": {
                "description": "포스트 조회 API",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "posts"
                ],
                "summary": "포스트 조회",
                "operationId": "posts.find",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "포스트 ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "포스트 조회 성공",
                        "schema": {
                            "$ref": "#/definitions/internal_adapter_rest.PostResource"
                        }
                    },
                    "400": {
                        "description": "잘못된 요청",
                        "schema": {
                            "$ref": "#/definitions/github_com_meteormin_friday_go_internal_app_errors.Error"
                        }
                    },
                    "500": {
                        "description": "서버 오류",
                        "schema": {
                            "$ref": "#/definitions/github_com_meteormin_friday_go_internal_app_errors.Error"
                        }
                    }
                }
            },
            "put": {
                "description": "포스트 수정 API",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "posts"
                ],
                "summary": "포스트 수정",
                "operationId": "posts.update",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "포스트 ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "포스트 수정 정보",
                        "name": "req",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/internal_adapter_rest.UpdatePostRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "포스트 수정 성공",
                        "schema": {
                            "$ref": "#/definitions/internal_adapter_rest.PostResource"
                        }
                    },
                    "400": {
                        "description": "잘못된 요청",
                        "schema": {
                            "$ref": "#/definitions/github_com_meteormin_friday_go_internal_app_errors.Error"
                        }
                    },
                    "500": {
                        "description": "서버 오류",
                        "schema": {
                            "$ref": "#/definitions/github_com_meteormin_friday_go_internal_app_errors.Error"
                        }
                    }
                }
            },
            "delete": {
                "description": "포스트 삭제 API",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "posts"
                ],
                "summary": "포스트 삭제",
                "operationId": "posts.delete",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "포스트 ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "포스트 삭제 성공",
                        "schema": {
                            "$ref": "#/definitions/internal_adapter_rest.PostResource"
                        }
                    },
                    "404": {
                        "description": "존재하지 않는 포스트",
                        "schema": {
                            "$ref": "#/definitions/github_com_meteormin_friday_go_internal_app_errors.Error"
                        }
                    },
                    "500": {
                        "description": "서버 오류",
                        "schema": {
                            "$ref": "#/definitions/github_com_meteormin_friday_go_internal_app_errors.Error"
                        }
                    }
                }
            }
        },
        "/api/sites": {
            "post": {
                "description": "사이트 생성 API",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "sites"
                ],
                "summary": "사이트 생성",
                "operationId": "sites.create",
                "parameters": [
                    {
                        "description": "사이트 생성 정보",
                        "name": "req",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/internal_adapter_rest.CreateSiteRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "사이트 생성 성공",
                        "schema": {
                            "$ref": "#/definitions/internal_adapter_rest.SiteResource"
                        }
                    },
                    "400": {
                        "description": "잘못된 요청",
                        "schema": {
                            "$ref": "#/definitions/github_com_meteormin_friday_go_internal_app_errors.Error"
                        }
                    },
                    "409": {
                        "description": "이메일 중복",
                        "schema": {
                            "$ref": "#/definitions/github_com_meteormin_friday_go_internal_app_errors.Error"
                        }
                    },
                    "500": {
                        "description": "서버 오류",
                        "schema": {
                            "$ref": "#/definitions/github_com_meteormin_friday_go_internal_app_errors.Error"
                        }
                    }
                }
            }
        },
        "/api/sites/{id}": {
            "get": {
                "description": "사이트 조회 API",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "sites"
                ],
                "summary": "사이트 조회",
                "operationId": "sites.find",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "사이트 ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "사이트 조회 성공",
                        "schema": {
                            "$ref": "#/definitions/internal_adapter_rest.SiteResource"
                        }
                    },
                    "400": {
                        "description": "잘못된 요청",
                        "schema": {
                            "$ref": "#/definitions/github_com_meteormin_friday_go_internal_app_errors.Error"
                        }
                    },
                    "404": {
                        "description": "사이트 없음",
                        "schema": {
                            "$ref": "#/definitions/github_com_meteormin_friday_go_internal_app_errors.Error"
                        }
                    }
                }
            },
            "put": {
                "description": "사이트 수정 API",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "sites"
                ],
                "summary": "사이트 수정",
                "operationId": "sites.update",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "사이트 ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "사이트 수정 정보",
                        "name": "req",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/internal_adapter_rest.UpdateSiteRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "사이트 수정 성공",
                        "schema": {
                            "$ref": "#/definitions/internal_adapter_rest.SiteResource"
                        }
                    },
                    "400": {
                        "description": "잘못된 요청",
                        "schema": {
                            "$ref": "#/definitions/github_com_meteormin_friday_go_internal_app_errors.Error"
                        }
                    },
                    "404": {
                        "description": "사이트 없음",
                        "schema": {
                            "$ref": "#/definitions/github_com_meteormin_friday_go_internal_app_errors.Error"
                        }
                    },
                    "500": {
                        "description": "서버 오류",
                        "schema": {
                            "$ref": "#/definitions/github_com_meteormin_friday_go_internal_app_errors.Error"
                        }
                    }
                }
            },
            "delete": {
                "description": "사이트 삭제 API",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "sites"
                ],
                "summary": "사이트 삭제",
                "operationId": "sites.delete",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "사이트 ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "사이트 삭제 성공",
                        "schema": {
                            "$ref": "#/definitions/internal_adapter_rest.SiteResource"
                        }
                    },
                    "400": {
                        "description": "잘못된 요청",
                        "schema": {
                            "$ref": "#/definitions/github_com_meteormin_friday_go_internal_app_errors.Error"
                        }
                    },
                    "404": {
                        "description": "사이트 없음",
                        "schema": {
                            "$ref": "#/definitions/github_com_meteormin_friday_go_internal_app_errors.Error"
                        }
                    },
                    "500": {
                        "description": "서버 오류",
                        "schema": {
                            "$ref": "#/definitions/github_com_meteormin_friday_go_internal_app_errors.Error"
                        }
                    }
                }
            }
        },
        "/api/sites/{id}/posts": {
            "get": {
                "description": "사이트 포스트 리스트 조회 API",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "sites"
                ],
                "summary": "사이트 포스트 리스트 조회",
                "operationId": "sites.retrievePosts",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "사이트 ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "사이트 포스트 리스트 조회 성공",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/internal_adapter_rest.PostResource"
                            }
                        }
                    },
                    "400": {
                        "description": "잘못된 요청",
                        "schema": {
                            "$ref": "#/definitions/github_com_meteormin_friday_go_internal_app_errors.Error"
                        }
                    },
                    "404": {
                        "description": "사이트 없음",
                        "schema": {
                            "$ref": "#/definitions/github_com_meteormin_friday_go_internal_app_errors.Error"
                        }
                    }
                }
            }
        },
        "/api/upload-file": {
            "post": {
                "description": "파일 업로드 API",
                "consumes": [
                    "multipart/form-data"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "upload-file"
                ],
                "summary": "파일 업로드",
                "operationId": "files.upload",
                "parameters": [
                    {
                        "type": "file",
                        "description": "파일",
                        "name": "file",
                        "in": "formData",
                        "required": true
                    }
                ],
                "responses": {
                    "201": {
                        "description": "파일 업로드 성공",
                        "schema": {
                            "$ref": "#/definitions/internal_adapter_rest.UploadFileResponse"
                        }
                    },
                    "400": {
                        "description": "잘못된 요청",
                        "schema": {
                            "$ref": "#/definitions/github_com_meteormin_friday_go_internal_app_errors.Error"
                        }
                    },
                    "500": {
                        "description": "서버 오류",
                        "schema": {
                            "$ref": "#/definitions/github_com_meteormin_friday_go_internal_app_errors.Error"
                        }
                    }
                }
            }
        },
        "/api/users": {
            "get": {
                "description": "회원 리스트 조회 API",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "users"
                ],
                "summary": "회원 리스트 조회",
                "operationId": "users",
                "responses": {
                    "200": {
                        "description": "회원 리스트 조회 성공",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/internal_adapter_rest.UserResource"
                            }
                        }
                    },
                    "500": {
                        "description": "서버 오류",
                        "schema": {
                            "$ref": "#/definitions/github_com_meteormin_friday_go_internal_app_errors.Error"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "github_com_meteormin_friday_go_internal_app_errors.Error": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer"
                },
                "message": {
                    "type": "string"
                },
                "title": {
                    "type": "string"
                }
            }
        },
        "internal_adapter_rest.CreatePostRequest": {
            "description": "생성 요청",
            "type": "object",
            "properties": {
                "content": {
                    "type": "string"
                },
                "fileId": {
                    "type": "integer"
                },
                "siteId": {
                    "type": "integer"
                },
                "tags": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "title": {
                    "type": "string"
                }
            }
        },
        "internal_adapter_rest.CreateSiteRequest": {
            "type": "object",
            "properties": {
                "host": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                }
            }
        },
        "internal_adapter_rest.PostResource": {
            "type": "object",
            "properties": {
                "content": {
                    "type": "string"
                },
                "created_at": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "tags": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "title": {
                    "type": "string"
                },
                "updated_at": {
                    "type": "string"
                },
                "uri": {
                    "type": "string"
                }
            }
        },
        "internal_adapter_rest.SignInRequest": {
            "description": "로그인 요청",
            "type": "object",
            "properties": {
                "password": {
                    "type": "string"
                },
                "username": {
                    "type": "string"
                }
            }
        },
        "internal_adapter_rest.SignupRequest": {
            "description": "가입 요청",
            "type": "object",
            "properties": {
                "name": {
                    "type": "string"
                },
                "password": {
                    "type": "string"
                },
                "username": {
                    "type": "string"
                }
            }
        },
        "internal_adapter_rest.SiteResource": {
            "type": "object",
            "properties": {
                "host": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "name": {
                    "type": "string"
                }
            }
        },
        "internal_adapter_rest.TokenResource": {
            "description": "토큰 정보 리소스",
            "type": "object",
            "properties": {
                "exp": {
                    "type": "integer"
                },
                "token": {
                    "type": "string"
                }
            }
        },
        "internal_adapter_rest.UpdatePostRequest": {
            "type": "object",
            "properties": {
                "content": {
                    "type": "string"
                },
                "fileId": {
                    "type": "integer"
                },
                "tags": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "title": {
                    "type": "string"
                }
            }
        },
        "internal_adapter_rest.UpdateSiteRequest": {
            "type": "object",
            "properties": {
                "name": {
                    "type": "string"
                }
            }
        },
        "internal_adapter_rest.UploadFileResponse": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "integer"
                },
                "url": {
                    "type": "string"
                }
            }
        },
        "internal_adapter_rest.UserResource": {
            "description": "회원 정보 리소스",
            "type": "object",
            "properties": {
                "createdAt": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "updatedAt": {
                    "type": "string"
                },
                "username": {
                    "type": "string"
                }
            }
        }
    },
    "securityDefinitions": {
        "BearerAuth": {
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        }
    },
    "tags": [
        {
            "name": "auth"
        },
        {
            "name": "users"
        },
        {
            "name": "upload-file"
        },
        {
            "name": "posts"
        }
    ]
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "{{.Version}}",
	Host:             "{{.Host}}",
	BasePath:         "/",
	Schemes:          []string{"http", "https"},
	Title:            "Friday.go API",
	Description:      "Friday.go API",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
