basePath: /
definitions:
  github_com_meteormin_friday_go_internal_app.Error:
    properties:
      code:
        type: integer
      message:
        type: string
      title:
        type: string
    type: object
  internal_adapter_rest_handler.CreatePostRequest:
    description: 생성 요청
    properties:
      content:
        type: string
      fileId:
        type: integer
      siteId:
        type: integer
      tags:
        items:
          type: string
        type: array
      title:
        type: string
    type: object
  internal_adapter_rest_handler.CreateSiteRequest:
    properties:
      host:
        type: string
      name:
        type: string
    type: object
  internal_adapter_rest_handler.PostResource:
    properties:
      content:
        type: string
      created_at:
        type: string
      fileId:
        type: integer
      id:
        type: integer
      tags:
        items:
          type: string
        type: array
      title:
        type: string
      updated_at:
        type: string
      uri:
        type: string
    type: object
  internal_adapter_rest_handler.SignInRequest:
    description: 로그인 요청
    properties:
      password:
        type: string
      username:
        type: string
    type: object
  internal_adapter_rest_handler.SignupRequest:
    description: 가입 요청
    properties:
      id:
        type: integer
      name:
        type: string
      password:
        type: string
      username:
        type: string
    type: object
  internal_adapter_rest_handler.SiteResource:
    properties:
      createdAt:
        type: string
      host:
        type: string
      id:
        type: integer
      name:
        type: string
      posts:
        items:
          $ref: '#/definitions/internal_adapter_rest_handler.PostResource'
        type: array
      updatedAt:
        type: string
    type: object
  internal_adapter_rest_handler.TokenResource:
    description: 토큰 정보 리소스
    properties:
      exp:
        type: integer
      token:
        type: string
    type: object
  internal_adapter_rest_handler.UpdatePostRequest:
    properties:
      content:
        type: string
      fileId:
        type: integer
      tags:
        items:
          type: string
        type: array
      title:
        type: string
    type: object
  internal_adapter_rest_handler.UpdateSiteRequest:
    properties:
      name:
        type: string
    type: object
  internal_adapter_rest_handler.UploadFileResponse:
    properties:
      id:
        type: integer
      uri:
        type: string
    type: object
  internal_adapter_rest_handler.UserResource:
    description: 회원 정보 리소스
    properties:
      createdAt:
        type: string
      id:
        type: integer
      name:
        type: string
      updatedAt:
        type: string
      username:
        type: string
    type: object
host: '{{.Host}}'
info:
  contact:
    email: miniyu97@gmail.com
    name: meteormin
    url: https://github.com/meteormin/friday.go
  description: Friday.go API
  title: Friday.go API
  version: '{{.Version}}'
paths:
  /api/auth/has-admin:
    get:
      consumes:
      - application/json
      description: 회원 관리자 여부 조회 API
      operationId: has-admin
      produces:
      - application/json
      responses:
        "200":
          description: 회원 관리자 여부 조회 성공
          schema:
            additionalProperties:
              type: boolean
            type: object
        "500":
          description: 서버 오류
          schema:
            $ref: '#/definitions/github_com_meteormin_friday_go_internal_app.Error'
      summary: 회원 관리자 여부 조회
      tags:
      - auth
  /api/auth/me:
    get:
      consumes:
      - application/json
      description: 회원 정보 조회 API
      operationId: me
      produces:
      - application/json
      responses:
        "200":
          description: 회원 정보 조회 성공
          schema:
            $ref: '#/definitions/internal_adapter_rest_handler.UserResource'
        "401":
          description: 로그인 정보 없음
          schema:
            $ref: '#/definitions/github_com_meteormin_friday_go_internal_app.Error'
        "500":
          description: 서버 오류
          schema:
            $ref: '#/definitions/github_com_meteormin_friday_go_internal_app.Error'
      security:
      - BearerAuth: []
      summary: 회원 정보 조회
      tags:
      - auth
  /api/auth/sign-in:
    post:
      consumes:
      - application/json
      description: 회원 로그인 API
      operationId: sign-in
      parameters:
      - description: 회원 로그인 정보
        in: body
        name: req
        required: true
        schema:
          $ref: '#/definitions/internal_adapter_rest_handler.SignInRequest'
      produces:
      - application/json
      responses:
        "200":
          description: 회원 로그인 성공
          schema:
            $ref: '#/definitions/internal_adapter_rest_handler.TokenResource'
        "400":
          description: 잘못된 요청
          schema:
            $ref: '#/definitions/github_com_meteormin_friday_go_internal_app.Error'
        "401":
          description: 로그인 실험
          schema:
            $ref: '#/definitions/github_com_meteormin_friday_go_internal_app.Error'
        "500":
          description: 서버 오류
          schema:
            $ref: '#/definitions/github_com_meteormin_friday_go_internal_app.Error'
      summary: 회원 로그인
      tags:
      - auth
  /api/auth/sign-up:
    post:
      consumes:
      - application/json
      description: 회원 가입 API
      operationId: sign-up
      parameters:
      - description: 회원 가입 정보
        in: body
        name: req
        required: true
        schema:
          $ref: '#/definitions/internal_adapter_rest_handler.SignupRequest'
      produces:
      - application/json
      responses:
        "201":
          description: 회원 가입 성공
          schema:
            $ref: '#/definitions/internal_adapter_rest_handler.UserResource'
        "400":
          description: 잘못된 요청" app.ErrInvalidUserPassword
          schema:
            $ref: '#/definitions/github_com_meteormin_friday_go_internal_app.Error'
        "409":
          description: 이메일 중복" app.ErrDuplicateUserUsername
          schema:
            $ref: '#/definitions/github_com_meteormin_friday_go_internal_app.Error'
        "500":
          description: 서버 오류
          schema:
            $ref: '#/definitions/github_com_meteormin_friday_go_internal_app.Error'
      summary: 회원 가입
      tags:
      - auth
  /api/posts:
    get:
      consumes:
      - application/json
      description: 포스트 리스트 조회 API
      operationId: posts.retrieve
      produces:
      - application/json
      responses:
        "200":
          description: 포스트 리스트 조회 성공
          schema:
            items:
              $ref: '#/definitions/internal_adapter_rest_handler.PostResource'
            type: array
        "500":
          description: 서버 오류
          schema:
            $ref: '#/definitions/github_com_meteormin_friday_go_internal_app.Error'
      security:
      - BearerAuth: []
      summary: 포스트 리스트 조회
      tags:
      - posts
    post:
      consumes:
      - application/json
      description: 포스트 생성 API
      operationId: posts.create
      parameters:
      - description: 포스트 생성 정보
        in: body
        name: req
        required: true
        schema:
          $ref: '#/definitions/internal_adapter_rest_handler.CreatePostRequest'
      produces:
      - application/json
      responses:
        "201":
          description: 포스트 생성 성공
          schema:
            $ref: '#/definitions/internal_adapter_rest_handler.PostResource'
        "400":
          description: 잘못된 요청
          schema:
            $ref: '#/definitions/github_com_meteormin_friday_go_internal_app.Error'
        "409":
          description: 이메일 중복
          schema:
            $ref: '#/definitions/github_com_meteormin_friday_go_internal_app.Error'
        "500":
          description: 서버 오류
          schema:
            $ref: '#/definitions/github_com_meteormin_friday_go_internal_app.Error'
      security:
      - BearerAuth: []
      summary: 포스트 생성
      tags:
      - posts
  /api/posts/{id}:
    delete:
      consumes:
      - application/json
      description: 포스트 삭제 API
      operationId: posts.delete
      parameters:
      - description: 포스트 ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "204":
          description: 포스트 삭제 성공
          schema:
            $ref: '#/definitions/internal_adapter_rest_handler.PostResource'
        "404":
          description: 존재하지 않는 포스트
          schema:
            $ref: '#/definitions/github_com_meteormin_friday_go_internal_app.Error'
        "500":
          description: 서버 오류
          schema:
            $ref: '#/definitions/github_com_meteormin_friday_go_internal_app.Error'
      security:
      - BearerAuth: []
      summary: 포스트 삭제
      tags:
      - posts
    get:
      consumes:
      - application/json
      description: 포스트 조회 API
      operationId: posts.find
      parameters:
      - description: 포스트 ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: 포스트 조회 성공
          schema:
            $ref: '#/definitions/internal_adapter_rest_handler.PostResource'
        "400":
          description: 잘못된 요청
          schema:
            $ref: '#/definitions/github_com_meteormin_friday_go_internal_app.Error'
        "500":
          description: 서버 오류
          schema:
            $ref: '#/definitions/github_com_meteormin_friday_go_internal_app.Error'
      security:
      - BearerAuth: []
      summary: 포스트 조회
      tags:
      - posts
    put:
      consumes:
      - application/json
      description: 포스트 수정 API
      operationId: posts.update
      parameters:
      - description: 포스트 ID
        in: path
        name: id
        required: true
        type: integer
      - description: 포스트 수정 정보
        in: body
        name: req
        required: true
        schema:
          $ref: '#/definitions/internal_adapter_rest_handler.UpdatePostRequest'
      produces:
      - application/json
      responses:
        "200":
          description: 포스트 수정 성공
          schema:
            $ref: '#/definitions/internal_adapter_rest_handler.PostResource'
        "400":
          description: 잘못된 요청
          schema:
            $ref: '#/definitions/github_com_meteormin_friday_go_internal_app.Error'
        "500":
          description: 서버 오류
          schema:
            $ref: '#/definitions/github_com_meteormin_friday_go_internal_app.Error'
      security:
      - BearerAuth: []
      summary: 포스트 수정
      tags:
      - posts
  /api/sites:
    get:
      consumes:
      - application/json
      description: 사이트 리스트 조회 API
      operationId: sites.retrieve
      produces:
      - application/json
      responses:
        "200":
          description: 사이트 리스트 조회 성공
          schema:
            items:
              $ref: '#/definitions/internal_adapter_rest_handler.SiteResource'
            type: array
        "400":
          description: 잘못된 요청
          schema:
            $ref: '#/definitions/github_com_meteormin_friday_go_internal_app.Error'
        "500":
          description: 서버 오류
          schema:
            $ref: '#/definitions/github_com_meteormin_friday_go_internal_app.Error'
      security:
      - BearerAuth: []
      summary: 사이트 리스트 조회
      tags:
      - sites
    post:
      consumes:
      - application/json
      description: 사이트 생성 API
      operationId: sites.create
      parameters:
      - description: 사이트 생성 정보
        in: body
        name: req
        required: true
        schema:
          $ref: '#/definitions/internal_adapter_rest_handler.CreateSiteRequest'
      produces:
      - application/json
      responses:
        "201":
          description: 사이트 생성 성공
          schema:
            $ref: '#/definitions/internal_adapter_rest_handler.SiteResource'
        "400":
          description: 잘못된 요청
          schema:
            $ref: '#/definitions/github_com_meteormin_friday_go_internal_app.Error'
        "409":
          description: 이메일 중복
          schema:
            $ref: '#/definitions/github_com_meteormin_friday_go_internal_app.Error'
        "500":
          description: 서버 오류
          schema:
            $ref: '#/definitions/github_com_meteormin_friday_go_internal_app.Error'
      security:
      - BearerAuth: []
      summary: 사이트 생성
      tags:
      - sites
  /api/sites/{id}:
    delete:
      consumes:
      - application/json
      description: 사이트 삭제 API
      operationId: sites.delete
      parameters:
      - description: 사이트 ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "204":
          description: 사이트 삭제 성공
          schema:
            $ref: '#/definitions/internal_adapter_rest_handler.SiteResource'
        "400":
          description: 잘못된 요청
          schema:
            $ref: '#/definitions/github_com_meteormin_friday_go_internal_app.Error'
        "404":
          description: 사이트 없음
          schema:
            $ref: '#/definitions/github_com_meteormin_friday_go_internal_app.Error'
        "500":
          description: 서버 오류
          schema:
            $ref: '#/definitions/github_com_meteormin_friday_go_internal_app.Error'
      security:
      - BearerAuth: []
      summary: 사이트 삭제
      tags:
      - sites
    get:
      consumes:
      - application/json
      description: 사이트 조회 API
      operationId: sites.find
      parameters:
      - description: 사이트 ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: 사이트 조회 성공
          schema:
            $ref: '#/definitions/internal_adapter_rest_handler.SiteResource'
        "400":
          description: 잘못된 요청
          schema:
            $ref: '#/definitions/github_com_meteormin_friday_go_internal_app.Error'
        "404":
          description: 사이트 없음
          schema:
            $ref: '#/definitions/github_com_meteormin_friday_go_internal_app.Error'
      security:
      - BearerAuth: []
      summary: 사이트 조회
      tags:
      - sites
    put:
      consumes:
      - application/json
      description: 사이트 수정 API
      operationId: sites.update
      parameters:
      - description: 사이트 ID
        in: path
        name: id
        required: true
        type: integer
      - description: 사이트 수정 정보
        in: body
        name: req
        required: true
        schema:
          $ref: '#/definitions/internal_adapter_rest_handler.UpdateSiteRequest'
      produces:
      - application/json
      responses:
        "200":
          description: 사이트 수정 성공
          schema:
            $ref: '#/definitions/internal_adapter_rest_handler.SiteResource'
        "400":
          description: 잘못된 요청
          schema:
            $ref: '#/definitions/github_com_meteormin_friday_go_internal_app.Error'
        "404":
          description: 사이트 없음
          schema:
            $ref: '#/definitions/github_com_meteormin_friday_go_internal_app.Error'
        "500":
          description: 서버 오류
          schema:
            $ref: '#/definitions/github_com_meteormin_friday_go_internal_app.Error'
      security:
      - BearerAuth: []
      summary: 사이트 수정
      tags:
      - sites
  /api/sites/{id}/posts:
    get:
      consumes:
      - application/json
      description: 사이트 포스트 리스트 조회 API
      operationId: sites.retrievePosts
      parameters:
      - description: 사이트 ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: 사이트 포스트 리스트 조회 성공
          schema:
            items:
              $ref: '#/definitions/internal_adapter_rest_handler.PostResource'
            type: array
        "400":
          description: 잘못된 요청
          schema:
            $ref: '#/definitions/github_com_meteormin_friday_go_internal_app.Error'
        "404":
          description: 사이트 없음
          schema:
            $ref: '#/definitions/github_com_meteormin_friday_go_internal_app.Error'
      security:
      - BearerAuth: []
      summary: 사이트 포스트 리스트 조회
      tags:
      - sites
  /api/upload-file:
    post:
      consumes:
      - multipart/form-data
      description: 파일 업로드 API
      operationId: files.upload
      parameters:
      - description: 파일
        in: formData
        name: file
        required: true
        type: file
      produces:
      - application/json
      responses:
        "201":
          description: 파일 업로드 성공
          schema:
            $ref: '#/definitions/internal_adapter_rest_handler.UploadFileResponse'
        "400":
          description: 잘못된 요청
          schema:
            $ref: '#/definitions/github_com_meteormin_friday_go_internal_app.Error'
        "500":
          description: 서버 오류
          schema:
            $ref: '#/definitions/github_com_meteormin_friday_go_internal_app.Error'
      security:
      - BearerAuth: []
      summary: 파일 업로드
      tags:
      - upload-file
  /api/upload-file/{id}:
    get:
      description: 파일 다운로드 API
      operationId: files.download
      parameters:
      - description: 파일 ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/octet-stream
      responses:
        "200":
          description: 파일 다운로드 성공
          schema:
            items:
              type: integer
            type: array
        "400":
          description: 잘못된 요청
          schema:
            $ref: '#/definitions/github_com_meteormin_friday_go_internal_app.Error'
        "404":
          description: 파일 없음
          schema:
            $ref: '#/definitions/github_com_meteormin_friday_go_internal_app.Error'
        "500":
          description: 서버 오류
          schema:
            $ref: '#/definitions/github_com_meteormin_friday_go_internal_app.Error'
      security:
      - BearerAuth: []
      summary: 파일 다운로드
      tags:
      - upload-file
  /api/users:
    get:
      consumes:
      - application/json
      description: 회원 리스트 조회 API
      operationId: users
      produces:
      - application/json
      responses:
        "200":
          description: 회원 리스트 조회 성공
          schema:
            items:
              $ref: '#/definitions/internal_adapter_rest_handler.UserResource'
            type: array
        "500":
          description: 서버 오류
          schema:
            $ref: '#/definitions/github_com_meteormin_friday_go_internal_app.Error'
      summary: 회원 리스트 조회
      tags:
      - users
schemes:
- http
- https
securityDefinitions:
  BearerAuth:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
tags:
- name: auth
- name: users
- name: upload-file
- name: posts
